name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual run

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_achievements: yes
          plugin_achievements_only: >
            polyglot, stargazer, sponsor, deployer, member,
            pull-shark, pull-request, galileo, superstar, octonaut
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_lines: yes
